name: singleton-bool
version: 0.1.0.0
synopsis: Type level booleans
description: |
  Type level booleans.

  @singletons@ package provides similar functionality,
  but it has tight dependency constraints.
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: phadej/singleton-bool
category: Web
tested-with: GHC==7.4.2, GHC==7.6.3, GHC==7.8.4, GHC==7.10.3, GHC==8.0.1
extra-source-files:
- README.md

ghc-options: -Wall

dependencies:
  - base        >=4.5 && <4.10

library:
  source-dirs: src
